// SPDX-License-Identifier: MIT
// Copyright 2024-2026 National Payments Corporation of India
//! Locating, starting, health-checking and restarting AiNxt OS (`ainxt-runtimed`) as a child process.
//!
//! The console always starts the daemon in **`jwt-sso`** mode with a secret generated fresh at
//! console startup and written to a `0600` overlay in the console's own directory. That is the point:
//! under the default `trusted-gateway` posture the caller asserts its own role and clearance, so a
//! browser talking to `:8080` could claim `admin`. In `jwt-sso` the daemon only believes a signed
//! token, and only the console can sign one.

use std::path::{Path, PathBuf};
use std::process::Stdio;

use tokio::process::{Child, Command};

/// Where the daemon binary is, having looked in the places a real install puts it.
pub fn locate_daemon(explicit: Option<&Path>) -> Result<PathBuf, String> {
    if let Some(p) = explicit {
        return if p.is_file() {
            Ok(p.to_path_buf())
        } else {
            Err(format!("--runtimed {} is not a file", p.display()))
        };
    }
    let mut candidates: Vec<PathBuf> = Vec::new();
    // Alongside this binary — how a packaged release ships them.
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            candidates.push(dir.join("ainxt-runtimed"));
            candidates.push(dir.join("ainxt-runtimed.exe"));
        }
    }
    // A developer's build tree.
    candidates.push(PathBuf::from("target/release/ainxt-runtimed"));
    candidates.push(PathBuf::from("target/debug/ainxt-runtimed"));

    for c in &candidates {
        if c.is_file() {
            return Ok(c.clone());
        }
    }
    Err(format!(
        "could not find the ainxt-runtimed binary. Looked in: {}.\n\
         Build it with:  cargo build --release -p ainxt-runtimed\n\
         or point at it: ainxt-os --runtimed /path/to/ainxt-runtimed",
        candidates
            .iter()
            .map(|c| c.display().to_string())
            .collect::<Vec<_>>()
            .join(", ")
    ))
}

/// 32 bytes of entropy, hex-encoded, for the console↔daemon shared HS256 secret.
pub fn generate_secret() -> String {
    let mut buf = [0u8; 32];
    #[cfg(unix)]
    {
        use std::io::Read;
        if let Ok(mut f) = std::fs::File::open("/dev/urandom") {
            if f.read_exact(&mut buf).is_ok() {
                return hex(&buf);
            }
        }
    }
    // Fallback: never reached on the platforms this console targets, but a weak secret on a
    // loopback-only listener beats refusing to start. Mixed so it is at least not guessable
    // from the clock alone.
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(std::process::id().to_le_bytes());
    h.update(
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or_default()
            .to_le_bytes(),
    );
    h.update((&buf as *const u8 as usize).to_le_bytes());
    eprintln!("ainxt-os: warning: /dev/urandom unavailable; using a weaker session secret");
    hex(&h.finalize())
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// Write the `jwt-sso` overlay the daemon is started with. Returns its path.
///
/// This is a *layer*, not a rewrite: the operator's own `runtimed.toml` is passed first and this
/// overlay second, so it only overrides the authenticator and the secret. Everything else the
/// operator configured still applies (AiNxt OS deep-merges `--config` layers in order).
pub fn write_auth_overlay(dir: &Path, secret: &str) -> std::io::Result<PathBuf> {
    std::fs::create_dir_all(dir)?;
    let path = dir.join("auth.overlay.toml");
    let body = format!(
        "# Generated by ainxt-os (the AiNxt OS Console) at each start. Do not edit; do not commit.\n\
         # The console is the authenticating gateway, so AiNxt OS is run in jwt-sso mode and only\n\
         # believes tokens the console signs. The secret is regenerated every start.\n\
         [server]\n\
         authenticator = \"jwt-sso\"\n\
         jwt_hs256_secret = \"{secret}\"\n"
    );
    std::fs::write(&path, body)?;
    crate::settings::restrict(&path)?;
    Ok(path)
}

pub struct Spawned {
    pub child: Child,
    pub log_path: PathBuf,
}

/// Start the daemon. Its ~80 lines of startup report go to a log file rather than the console's own
/// stdout, so an operator sees a clean "starting…" instead of a wall of subsystem text — but the log
/// is kept and surfaced in the Activity tab, because the report is genuinely useful.
pub async fn spawn(
    daemon: &Path,
    configs: &[PathBuf],
    env: &[(String, String)],
    state_dir: &Path,
) -> std::io::Result<Spawned> {
    std::fs::create_dir_all(state_dir)?;
    let log_path = state_dir.join("ainxt-os.log");
    let log = std::fs::File::create(&log_path)?;
    let errlog = log.try_clone()?;

    let mut cmd = Command::new(daemon);
    for c in configs {
        cmd.arg("--config").arg(c);
    }
    for (k, v) in env {
        cmd.env(k, v);
    }
    cmd.stdout(Stdio::from(log))
        .stderr(Stdio::from(errlog))
        .stdin(Stdio::null())
        .kill_on_drop(true);

    let child = cmd.spawn()?;
    Ok(Spawned { child, log_path })
}

/// Poll `GET /healthz` until AiNxt OS reports itself live, or give up.
///
/// A TCP connect would be the easy probe, and it is the wrong one: the socket is bound before the
/// daemon can serve a turn, so a successful handshake says nothing about whether composition
/// finished. `/healthz` only exists on a fully assembled router, so a `200` is the signal the
/// Console actually needs before it tells an operator to open a browser.
///
/// Backward compatibility: if the endpoint answers with anything other than `200`, the daemon is an
/// older build that predates `/healthz` — but HTTP is demonstrably serving, so treat that as ready
/// and say so once, rather than timing out against a runtime that works.
pub async fn wait_until_listening(port: u16, attempts: u32) -> bool {
    let url = format!("http://127.0.0.1:{port}/healthz");
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(2))
        .build()
        .unwrap_or_default();
    for _ in 0..attempts {
        match client.get(&url).send().await {
            Ok(r) if r.status().is_success() => return true,
            Ok(r) => {
                eprintln!(
                    "ainxt-os: note: /healthz answered {} — this AiNxt OS build predates the health \
                     endpoint; treating a served HTTP response as ready",
                    r.status().as_u16()
                );
                return true;
            }
            Err(_) => {}
        }
        tokio::time::sleep(std::time::Duration::from_millis(250)).await;
    }
    false
}

/// Run `--check` against a candidate config and return the daemon's own verdict.
///
/// Used before a Settings save is committed: the daemon is the authority on whether a config is
/// valid, so the console asks it rather than reimplementing the rules.
pub async fn validate_config(
    daemon: &Path,
    configs: &[PathBuf],
    env: &[(String, String)],
) -> Result<String, String> {
    let mut cmd = Command::new(daemon);
    for c in configs {
        cmd.arg("--config").arg(c);
    }
    cmd.arg("--check");
    for (k, v) in env {
        cmd.env(k, v);
    }
    let out = cmd
        .output()
        .await
        .map_err(|e| format!("could not run AiNxt OS --check: {e}"))?;
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    let stderr = String::from_utf8_lossy(&out.stderr).to_string();
    if out.status.success() {
        Ok(stdout)
    } else {
        // The daemon's refusal messages are written for humans; pass the last one through.
        let msg = stderr
            .lines()
            .chain(stdout.lines())
            .filter(|l| l.contains("error"))
            .last()
            .unwrap_or("configuration was rejected")
            .trim()
            .to_string();
        Err(msg)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_secrets_are_long_and_distinct() {
        let a = generate_secret();
        let b = generate_secret();
        assert_eq!(a.len(), 64, "32 bytes hex-encoded");
        assert_ne!(a, b, "a fresh secret per start is the point");
        assert!(a.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn overlay_selects_jwt_sso_and_is_owner_only() {
        let dir = std::env::temp_dir().join(format!("ainxt-console-ovl-{}", std::process::id()));
        let p = write_auth_overlay(&dir, "deadbeef").expect("write");
        let body = std::fs::read_to_string(&p).expect("read");
        assert!(body.contains(r#"authenticator = "jwt-sso""#));
        assert!(body.contains(r#"jwt_hs256_secret = "deadbeef""#));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&p).expect("stat").permissions().mode();
            assert_eq!(mode & 0o777, 0o600, "the overlay holds the signing secret");
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn locate_reports_where_it_looked_when_it_fails() {
        let err = locate_daemon(Some(Path::new("/definitely/not/here"))).unwrap_err();
        assert!(err.contains("not a file"));
    }
}
