// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 National Payments Corporation of India
//! r11_sdk_emit — the headless CLI materializes the Python/TS SDK bindings fully offline.
//!
//! The CLI is a thin wrapper over the Rust SDK; `ainxt sdk emit <lang>` / `ainxt sdk contract` run
//! the contract codegen with no network or model, so an air-gapped/CI box can regenerate the Python
//! (first) and TypeScript SDK sources from the one wire contract. This proves the generation path is
//! reachable and deterministic; publishing + `pytest`/`vitest` CI + the live transport are infra.

use ainxt_cli::{run_cli, EXIT_OK, EXIT_USAGE};

fn emit(argv: &[&str]) -> (i32, String) {
    let argv: Vec<String> = argv.iter().map(|s| s.to_string()).collect();
    let mut out: Vec<u8> = Vec::new();
    let rt = tokio::runtime::Builder::new_current_thread()
        .build()
        .unwrap();
    let code = rt.block_on(run_cli(&argv, "", &mut out));
    (code, String::from_utf8(out).unwrap())
}

#[test]
fn r11_cli_emits_python_sdk_offline() {
    let (code, text) = emit(&["sdk", "emit", "python"]);
    assert_eq!(code, EXIT_OK);
    assert!(text.contains("GENERATED by ainxt-client"));
    assert!(text.contains("PROTOCOL_VERSION ="));
    assert!(text.contains("class Runtime"));
    assert!(text.contains("class Harness"));
    // A representative typed event + the tool-call vocabulary are present.
    assert!(text.contains("\"text.delta\":"));
    assert!(text.contains("\"tool.call.start\":"));
    assert!(
        text.contains("\"turn.submit\","),
        "commands must be emitted"
    );
}

#[test]
fn r11_cli_emits_typescript_sdk_offline() {
    let (code, text) = emit(&["sdk", "emit", "ts"]);
    assert_eq!(code, EXIT_OK);
    assert!(text.contains("export type WireEvent ="));
    assert!(text.contains("export type ErrorCategory ="));
    assert!(text.contains("export class Runtime"));
    assert!(text.contains("type: \"text.delta\";"));
}

#[test]
fn r11_cli_emits_contract_descriptor_json() {
    let (code, text) = emit(&["sdk", "contract"]);
    assert_eq!(code, EXIT_OK);
    // It's valid JSON carrying the events/commands/error taxonomy.
    let v: serde_json::Value = serde_json::from_str(&text).unwrap();
    assert!(v.get("events").and_then(|e| e.as_array()).is_some());
    assert!(v.get("commands").and_then(|c| c.as_array()).is_some());
    assert!(v.get("protocol_version").is_some());
    assert!(v.get("error_categories").is_some());
}

#[test]
fn r11_cli_rejects_unknown_sdk_language() {
    let (code, text) = emit(&["sdk", "emit", "cobol"]);
    assert_eq!(code, EXIT_USAGE);
    assert!(text.contains("unknown sdk language"));
}
