// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 National Payments Corporation of India
//! **Automation-complacency / oversight-health controls** (WORKFORCE_AND_OS §7).
//!
//! §5's "a named human is accountable and oversees it" only holds if that human's oversight stays
//! *real*. As roles automate, maker-checker degrades silently into rubber-stamping. Three controls,
//! all pure logic here:
//!
//! 1. [`oversight_health`] — per approver×role **approve-latency** and **override-rate**; a
//!    rising-volume trend where override-rate → 0 with sub-read-time latency is the complacency
//!    signature (flagged amber).
//! 2. [`AttentionCheck`] — Breaker-generated **decoys** injected into high-stakes approval queues; an
//!    approved decoy is an immediate incident + mandatory-retraining flag.
//! 3. [`competency_route`] — an expired competency status **re-routes** a high-stakes approval to a
//!    secondary approver rather than blocking (a competency gate must never itself become an outage).

use std::collections::BTreeMap;

use crate::role::PaymentBoundary;

// ============================ §7.1 approve-latency / override-rate ============================

/// One HITL approval decision, already logged to the Event Log (ADR-003).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ApprovalEvent {
    pub approver: String,
    pub role: String,
    /// Seconds from surfaced-for-review to decision.
    pub latency_secs: u64,
    /// The artifact's minimum plausible read time; a decision faster than this is itself a signal.
    pub min_read_secs: u64,
    /// The decision changed/rejected the proposal (true) vs rubber-stamped it (false).
    pub overridden: bool,
}

/// Derived oversight-health metrics for one approver×role pair.
#[derive(Debug, Clone, PartialEq)]
pub struct OversightMetrics {
    pub approver: String,
    pub role: String,
    pub count: usize,
    pub median_latency_secs: u64,
    pub override_rate: f64,
    /// The complacency signature: enough volume, median latency below read-time, override-rate 0.
    pub amber: bool,
}

/// Derive per approver×role metrics. `min_count` is the volume below which the signal is not yet
/// powered (no amber). Deterministic; input order does not affect the medians.
pub fn oversight_health(events: &[ApprovalEvent], min_count: usize) -> Vec<OversightMetrics> {
    // Group by (approver, role).
    let mut groups: BTreeMap<(String, String), Vec<&ApprovalEvent>> = BTreeMap::new();
    for e in events {
        groups
            .entry((e.approver.clone(), e.role.clone()))
            .or_default()
            .push(e);
    }

    let mut out = Vec::new();
    for ((approver, role), evs) in groups {
        let count = evs.len();
        let mut lat: Vec<u64> = evs.iter().map(|e| e.latency_secs).collect();
        lat.sort_unstable();
        let median = median_u64(&lat);
        let overrides = evs.iter().filter(|e| e.overridden).count();
        let override_rate = overrides as f64 / count as f64;
        // Read-time floor for this pair = the strictest (min) declared min_read across its events.
        let read_floor = evs.iter().map(|e| e.min_read_secs).min().unwrap_or(0);
        let amber = count >= min_count && median < read_floor && override_rate == 0.0;
        out.push(OversightMetrics {
            approver,
            role,
            count,
            median_latency_secs: median,
            override_rate,
            amber,
        });
    }
    out
}

fn median_u64(sorted: &[u64]) -> u64 {
    if sorted.is_empty() {
        return 0;
    }
    let n = sorted.len();
    if n % 2 == 1 {
        sorted[n / 2]
    } else {
        // Even count: mean of the two central values (integer).
        (sorted[n / 2 - 1] + sorted[n / 2]) / 2
    }
}

// ============================ §7.2 verification attention-checks (decoys) ============================

/// A synthetic known-bad case generated by the Breaker and injected into a high-stakes approval
/// queue. It is engineered to require *rejection*: the correct action is always to reject it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AttentionCheck {
    pub decoy_id: String,
    pub role: String,
}

/// Should a decoy be injected? Only for high-stakes approvals: at the payment boundary, or on
/// regulated-payment / PII data (§7.2). The caller injects *unpredictably*; this only decides
/// eligibility.
pub fn should_inject_decoy(
    payment_boundary: PaymentBoundary,
    data_class: ainxt_types::DataClass,
) -> bool {
    payment_boundary.is_high_stakes() || data_class.is_regulated()
}

/// The outcome of an attention-check.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DecoyOutcome {
    /// The approver rejected the decoy — invisible to them, the probe stays a genuine test.
    CorrectlyRejected,
    /// The approver *approved* a known-bad case — a hard-fail incident.
    Incident {
        approver: String,
        mandatory_retraining: bool,
    },
}

/// A decoy actually **generated by the Breaker's own adversarial corpus** ([`crate::breaker::Breaker`])
/// for a specific role, rather than an [`AttentionCheck`] the approval-queue caller invents by hand.
/// Before this, nothing derived `decoy_id` from real content — a caller was free to construct
/// `AttentionCheck { decoy_id: "d1", .. }` with an arbitrary label, so "Breaker-generated" was aspirational
/// prose, not an enforced property. [`generate_decoy`] closes that: the decoy IS one of the role's own
/// generated adversarial cases (the injection / over-privilege / PII-exfiltration probes the Breaker
/// gates publish with), so an approver who passes it is provably failing the same bar the role itself
/// had to clear.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedDecoy {
    pub check: AttentionCheck,
    /// The underlying Breaker adversarial case the decoy content came from (for audit / replay).
    pub case: crate::breaker::AdversarialCase,
}

/// Generate a §7.2 attention-check decoy from the Breaker's own adversarial corpus
/// ([`crate::breaker::Breaker::adversarial_corpus`]) for `role`: picks the first case whose correct
/// action is a hard refusal (`MustRefuse` or `MustNotLeakPii`) — a genuine known-bad probe, not an
/// invented one — so the injected decoy is real Breaker material. Returns `None` only when the role's
/// corpus contains no such case (e.g. it ingests no external data and touches no PII, so there is
/// nothing adversarial to decoy with); eligibility to inject AT ALL is still gated separately by
/// [`should_inject_decoy`].
pub fn generate_decoy(role: &crate::role::ValidatedRole) -> Option<GeneratedDecoy> {
    let corpus = crate::breaker::Breaker::adversarial_corpus(role);
    let case = corpus.into_iter().find(|c| {
        matches!(
            c.expect,
            crate::breaker::Expectation::MustRefuse | crate::breaker::Expectation::MustNotLeakPii
        )
    })?;
    Some(GeneratedDecoy {
        check: AttentionCheck {
            decoy_id: case.id.clone(),
            role: role.id().to_string(),
        },
        case,
    })
}

/// Evaluate an approver's response to an injected decoy. Approving a decoy is never "just a data
/// point": it is an immediate incident + a mandatory-retraining flag routed to the manager.
pub fn evaluate_decoy(check: &AttentionCheck, approver: &str, approved: bool) -> DecoyOutcome {
    let _ = check;
    if approved {
        DecoyOutcome::Incident {
            approver: approver.to_string(),
            mandatory_retraining: true,
        }
    } else {
        DecoyOutcome::CorrectlyRejected
    }
}

// ============================ §7.3 competency maintenance ============================

/// An approver's competency status (data-plane).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompetencyStatus {
    Current,
    /// Sat at ~0 override-rate for too long, or failed an attention-check.
    Expired,
}

/// Derive competency: expired if a decoy was failed, or override-rate has been ~0 across at least `n`
/// consecutive high-stakes approvals.
pub fn competency_after(
    consecutive_zero_override: usize,
    n: usize,
    failed_attention_check: bool,
) -> CompetencyStatus {
    if failed_attention_check || (n > 0 && consecutive_zero_override >= n) {
        CompetencyStatus::Expired
    } else {
        CompetencyStatus::Current
    }
}

/// Where a high-stakes approval is routed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ApprovalRoute {
    /// Honoured by the primary approver.
    Primary(String),
    /// Re-routed to the designated secondary because the primary's competency expired (§7.3). The
    /// workflow is NOT blocked — a competency gate must never itself become an outage.
    Rerouted {
        from: String,
        to: String,
        reason: String,
    },
}

/// Route a high-stakes approval per the primary's competency status. An expired status re-routes to
/// the secondary; a current status is honoured by the primary. The Policy Engine (ADR-003) calls this
/// at approval-dispatch time exactly as it checks `execute_rbac`.
pub fn competency_route(
    primary: &str,
    primary_status: CompetencyStatus,
    secondary: &str,
) -> ApprovalRoute {
    match primary_status {
        CompetencyStatus::Current => ApprovalRoute::Primary(primary.to_string()),
        CompetencyStatus::Expired => ApprovalRoute::Rerouted {
            from: primary.to_string(),
            to: secondary.to_string(),
            reason: "competency_status: expired".to_string(),
        },
    }
}
